# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY modelAssembly.py modelAssembly.py
COPY ssdToolbox.py ssdToolbox.py

ENV PYTHONUNBUFFERED 1

ENTRYPOINT ["python", "modelAssembly.py"]
