# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY dummy.csv dummy.csv
COPY dataService.py dataService.py

ENV PYTHONUNBUFFERED 1

ENTRYPOINT ["python", "dataService.py"]
